name: Continuous Integration (CI)
on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".git/**"
      - "CODE_OF_CONFUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
jobs:
  build-source-code:
    name: Build source code
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@3
        with:
          java-version: 17
          #distribution: 'adopt'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0          

      - name: grant execute permission for gradlew 
        run: chmod +x gradlew
        shell: bash

      - name: build gradle
        #run: ./gradlew clean build
        run: ./gradlew build -x test
        shell: bash

  build-container-image:
    name: Build a container image
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Test Echo
        run: echo 'test String - build start'

      - name: grant execute permission for gradlew 
        run: chmod +x gradlew
        shell: bash

      - name: build gradle
        #run: ./gradlew clean build
        run: ./gradlew build -x test
        shell: bash

      - name: Build image
        env:
          IMAGE_NAME: ${{ github.event.repository.name }}
        run: docker build . --file Dockerfile --tag $IMAGE_NAME



        